### PR TITLE
Public initializer for DefaultJSONSerializer

### PR DESCRIPTION
**Pull request by alex-alex**

### CODE REVIEW

**Comment by paulofaria** [comment]
`DefaultJSONSerializer` doesn't need to be public. It is called implicitly when you call `json.description`.

**Comment by alex-alex** [comment]
`json.description` is perfect for convenience, but if you need performance, I don't think it's a good idea to initialize new object every time (even if it doesn't store any properties)

**Comment by paulofaria** [comment]
In that case, could you please update to the style:

``` swift
public init() {}
```

It's the style used throughout Zewo. I saw it was your first take. I'm always unsure of which style to use it too. But I think this is better. And while you're at it. Could you create a public initializer for `PrettyJSONSerializer` too? And if it's not too much to ask, make it final? haha, this way you get even more contrib kudos! (:

Thanks, man!

**Comment by alex-alex** [comment]
`PrettyJSONSerializer` inherits initializer from `DefaultJSONSerializer`, so it's not necessary.

And thank you for doing these libraries.

**Comment by paulofaria** [comment]
Thanks, mate!

**Pull request merged**
